version: '3.8'

services:
  nexci:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-development}
    restart: unless-stopped 