services:
  - type: web
    name: nexci
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "pip install email_validator && gunicorn wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    plan: free
